student_names=["punith","yash","sagar","shrini","varun","jaswa","akhil","nk"];
print(student_names)
print("------")
print(student_names[3])
student_names.append("kajimola")
print(student_names)
student_names.remove("jaswa")
print(student_names)
student_names.remove("kajimola")
print(student_names)
student_names.insert(2,"kajimola")
print(student_names)
student_names.insert(6,"praju")
print(student_names)
student_names.insert(8,"chikkapa")
print(student_names)
student_names.pop(3)
print(student_names)
print(f"length of list:{len(student_names)}")
student_names.reverse()
print(f"reverse:(student_names)")

